### ISSUE TITLE
Potential for Branding Confusion

### ISSUE THREAD

**Issue by SDGNelson** [UnturnedStore/UnturnedStore#88]
Hello, we received a report from a player confused whether this is an official site. Could you include a disclaimer that it's not officially affiliated with SDG or Unturned please? As well as this text: `Unturned® is a registered trademark or trademark of Smartly Dressed Games Ltd. in the United States, Canada, and other countries.`

**Comment by Bradler26** [comment]
Hi.

I am currently on holiday right now but I will get our developer to add this on Monday.

**Comment by SDGNelson** [comment]
Thanks Brad!
